[package]
name = "simplebuffers-sanitycheck"
version = "0.1.2"
edition = "2021"
rust-version = "1.60"

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
simplebuffers-core = { path = "../simplebuffers-core" }
simplebuffers-codegen = { path = "../simplebuffers-codegen" }
